main:
    path: /
    defaults: { _controller: App\Controller\Crm\DefaultController::index }

administrators:
    path: /administrators
    defaults: { _controller: App\Controller\Crm\AdminController::index }

administrator_edit:
    path: /administrator/edit/{id}
    defaults: { _controller: App\Controller\Crm\AdminController::edit, id: null }